name: nanocaller_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools
  - parasail-python
  - muscle=3.8
  - numpy
  - pysam
  - python>=3.8
  - samtools>=1.10
  - tensorflow>=2.2
  - whatshap>=2.0
  - vcflib
  - intervaltree=3.*
  - tqdm
  - rtg-tools
